name: macos

on:
  workflow_dispatch:
  push:
    paths:
      - 'CMakeLists.txt'
      - 'dap/**'
      - 'dbgcli/**'
      - 'tests/**'
      - '.github/workflows/macos.yml'
  pull_request:
    paths:
      - 'CMakeLists.txt'
      - 'dap/**'
      - 'dbgcli/**'
      - 'tests/**'
      - '.github/workflows/macos.yml'

jobs:
  macos:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        wx-version: ['v3.2.8.1']

    steps:

    - name: Install wxDap's dependencies
      run: |
        brew install git || true
        brew install cmake || true
        brew install libssh || true
        brew install hunspell || true

    # WxWidgets
    - name: Checkout
      uses: actions/checkout@v4
      with:
          repository: wxWidgets/wxWidgets
          ref: ${{matrix.wx-version}}
          submodules: recursive
          path: wxWidgets

    - name: Build and install wxWidgets
      run: |
        mkdir wxWidgets/build-release
        cd wxWidgets/build-release
        cmake .. -DCMAKE_BUILD_TYPE=Release -DwxBUILD_DEBUG_LEVEL=0  -DwxBUILD_MONOLITHIC=1 -DwxUSE_SYS_LIBS=OFF -DwxUSE_LUNASVG=OFF -DwxUSE_STL=1
        make -j$(sysctl -n hw.physicalcpu)
        sudo make install

    # wxdap
    - name: Checkout wxdap
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build wxdap
      run: |
        mkdir build-release
        cd build-release
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=1
        cmake --build . -j $(sysctl -n hw.physicalcpu)

    - name: test
      run: |
        cd build-release
        ctest --output-on-failure
