name: msys2

on:
  workflow_dispatch:
  push:
    paths:
      - 'CMakeLists.txt'
      - 'dap/**'
      - 'dbgcli/**'
      - 'tests/**'
      - '.github/workflows/msys2.yml'
  pull_request:
    paths:
      - 'CMakeLists.txt'
      - 'dap/**'
      - 'dbgcli/**'
      - 'tests/**'
      - '.github/workflows/msys2.yml'

jobs:
  msys2:
    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2

    # pre-requires
    - name: Install dependencies
      shell: msys2 {0}
      run: |
        # pacman -Syu --noconfirm # Fail, requires to close this process
        pacman -S --noconfirm mingw-w64-clang-x86_64-cmake mingw-w64-clang-x86_64-make mingw-w64-clang-x86_64-clang

    # WxWidgets
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: wxWidgets/wxWidgets
        path: wxWidgets
        ref: v3.2.4
        submodules: recursive

    - name: build and install wxWidgets # gcc 32-bit so FIND_PACKAGE(wxWidgets) works
      shell: msys2 {0}
      run: |
        mkdir wxWidgets/build-release
        cd wxWidgets/build-release
        PATH="/clang64/bin:$PATH" cmake .. -G"MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$HOME/root" -DwxBUILD_DEBUG_LEVEL=0 -DwxBUILD_MONOLITHIC=0 -DwxBUILD_SAMPLES=SOME -DwxUSE_STL=1
        PATH="/clang64/bin:$PATH" mingw32-make -j$(nproc) && PATH="/clang64/bin:$PATH" mingw32-make install

    # wx-config-msys2
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: eranif/wx-config-msys2
        path: wx-config-msys2

    - name: build and install wx-config-msys2
      shell: msys2 {0}
      run: |
        mkdir wx-config-msys2/build-release
        cd wx-config-msys2/build-release
        PATH="/clang64/bin:$PATH" cmake .. -G"MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$HOME/root"
        PATH="/clang64/bin:$PATH" mingw32-make -j$(nproc) install
        #add $HOME/root/bin to PATH

    # wxdap
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: build wxdap
      shell: msys2 {0}
      run: |
        mkdir build-release
        cd build-release
        PATH="/clang64/bin:$HOME/root/bin:$PATH" cmake .. -G"MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=1 -DCL_WX_CONFIG=wx-config-msys2 -DWXWIN="$HOME/root"
        PATH="/clang64/bin:"$HOME/root/bin":$PATH" mingw32-make -j$(nproc)

    - name: test
      shell: msys2 {0}
      run: |
        cd build-release
        PATH="/clang64/bin:"$HOME/root/lib":$PATH" ctest --output-on-failure

    # Upload artefact
    - name: artifact
      uses: actions/upload-artifact@v4
      with:
        name: codelite
        path: |
          build-release/Release/**.*
          "$HOME/root/**/*"
