name: ubuntu

on:
  workflow_dispatch:
  push:
    paths:
      - 'CMakeLists.txt'
      - 'dap/**'
      - 'dbgcli/**'
      - 'tests/**'
      - '.github/workflows/ubuntu.yml'
  pull_request:
    paths:
      - 'CMakeLists.txt'
      - 'dap/**'
      - 'dbgcli/**'
      - 'tests/**'
      - '.github/workflows/ubuntu.yml'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    # WxWidgets
    - name: install dependencies for wxWidgets
      run: sudo apt-get install build-essential clang-format-12 cmake git libedit-dev libgtk-3-dev libhunspell-dev libsqlite3-dev libssh-dev pkg-config xterm

    - name: Checkout WxWidgets
      uses: actions/checkout@v4
      with:
        repository: wxWidgets/wxWidgets
        path: wxWidgets
        ref: v3.2.4
        submodules: recursive

    - name: build and install wxWidgets
      run: |
        mkdir -p wxWidgets/build-release
        cd wxWidgets/build-release
        ../configure --disable-debug_flag --with-gtk=3 --enable-stl
        make -j$(nproc) && sudo make install

    # wxdap
    - name: Checkout wxdap
      uses: actions/checkout@v4

    - name: build wxdap
      run: |
        mkdir build-release
        cd build-release
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=1
        cmake --build . -j $(nproc)

    - name: test
      run: |
        cd build-release
        ctest --output-on-failure
